name: Call the reusable workflow dotnet nuget prerelease

on:
  workflow_call:
  push:
    branches:
      - master

jobs:
  workflow-prerelease:
    uses: tiagomartimiano/github-nuget-prerelease-release-workflow/.github/workflows/dotnet-nuget-prerelease.yml@v1.0.0